SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO

CREATE    FUNCTION [dbo].[OUTLOOK_fn_Get_Email_Address](@Network_ID varchar(30), @Staff_CLassification_ID INT)
	RETURNS VARCHAR(100)
AS
BEGIN
	
		DECLARE @CAMPUS_EMAIL VARCHAR(100)
			
		SET @CAMPUS_EMAIL = '' 
	
		
		SELECT DISTINCT @CAMPUS_EMAIL = ISNULL(CAMPUS_EMAIL,'')
		FROM  dbo._DM_CONTACT  		
		WHERE   USERNAME = @Network_ID 
				

		RETURN @CAMPUS_EMAIL
END


GO
