SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO

-- NS 4/3/2017
CREATE FUNCTION [dbo].[Get_Course_Enrollment] 
(
	 @term_cd VARCHAR(6)
	 ,@CRN varchar(5)
	 ,@CRS_ID varchar(12)
	 ,@EDW_PERS_ID varchar(10)
	 ,@CRS_SUBJ_CD varchar(4)
	 ,@CRS_NBR Varchar(5)
	 ,@SECT_NBR varchar(3)
)
RETURNS INTEGER  AS  
BEGIN 
	
	DECLARE @CLASSROSTERCOUNT INT
	DECLARE @startdatetime datetime

	SELECT @CLASSROSTERCOUNT = Count(DISTINCT CRS_HIST.EDW_PERS_ID) 
			FROM DECISION_SUPPORT.dbo.EDW_T_STUDENT_CRS_REG_HIST CRS_HIST 	
			INNER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_SECT_BASE CRS_SECTION  
				INNER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_SECT_SESS TSS 
					INNER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_SESS TS 
						INNER JOIN DECISION_SUPPORT.dbo.EDW_T_FAC_INSTRN_ASSIGN TFIA 					 
							ON TS.CRS_ID = TFIA.CRS_ID AND 
							TS.TERM_CD = TFIA.TERM_CD AND 
							TS.SESS_ID = TFIA.SESS_ID 
						INNER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_TERM_CD PETTC 
							ON TS.TERM_CD = PETTC.TERM_CD AND 
							PETTC.TERM_CD_CAMPUS_CD = '100' -- UIUC				
						ON TSS.CRS_ID = TS.CRS_ID AND 
						TSS.TERM_CD = TS.TERM_CD AND 
						TSS.SESS_ID = TS.SESS_ID 
					ON CRS_SECTION.CRN = TSS.CRN AND 
					CRS_SECTION.CRS_ID = TSS.CRS_ID AND 
					CRS_SECTION.TERM_CD = TSS.TERM_CD AND 
					CRS_SECTION.SECT_STATUS_CD = 'A' 
				ON CRS_SECTION.CRS_ID = @CRS_ID AND 
				CRS_SECTION.TERM_CD = @TERM_CD	AND  
				CRS_HIST.STUDENT_CRS_REG_CUR_INFO_IND = 'Y' AND  
				CRS_HIST.TERM_CD = @TERM_CD 			
		WHERE 	TFIA.EDW_PERS_ID = @EDW_PERS_ID AND 
			CRS_HIST.STUDENT_CRS_REG_CUR_INFO_IND = 'Y' AND 
			CRS_HIST.TERM_CD = @TERM_CD AND  
			CRS_HIST.CRN = @CRN AND 
			TSS.CRN = @CRN AND 
			CRS_SECTION.CRS_NBR = @CRS_NBR AND 
			CRS_SECTION.CRS_SUBJ_CD = @CRS_SUBJ_CD AND 
			CRS_SECTION.SECT_NBR = @SECT_NBR 
			AND
			(CRS_HIST.CRN IN (
					SELECT DISTINCT PTSB.CRN 
					FROM DECISION_SUPPORT.dbo.PUBLIC_EDW_T_SECT_BASE PTSB
						INNER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_SECT_SESS SS 
							INNER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_SESS PTS 
								INNER JOIN DECISION_SUPPORT.dbo.EDW_T_FAC_INSTRN_ASSIGN FIA 					 
									ON PTS.CRS_ID = FIA.CRS_ID AND 
									PTS.TERM_CD = FIA.TERM_CD AND 
									PTS.SESS_ID = FIA.SESS_ID 
								INNER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_TERM_CD TC 
									ON PTS.TERM_CD = TC.TERM_CD AND 
									TC.TERM_CD_CAMPUS_CD = '100' -- UIUC				
								ON SS.CRS_ID = PTS.CRS_ID AND 
								SS.TERM_CD = PTS.TERM_CD AND 
								SS.SESS_ID = PTS.SESS_ID 
							ON PTSB.CRN = SS.CRN AND 
							PTSB.CRS_ID = SS.CRS_ID AND 
							PTSB.TERM_CD = SS.TERM_CD AND 
							PTSB.SECT_STATUS_CD = 'A' 
					WHERE PTSB.TERM_CD = @TERM_CD AND 
					PTSB.CRS_ID = @CRS_ID AND 
					FIA.EDW_PERS_ID = @EDW_PERS_ID AND 
					SS.CRN = @CRN AND 
					PTSB.CRN = @CRN 
					) 	
			)		

	/*
		print dbo.[__DM_fn_Course_Enrollment]('120048','10411',''''')
		print dbo.[__DM_fn_Course_Enrollment]('120155'......)
		
	*/
	RETURN @CLASSROSTERCOUNT
END





GO
