SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS OFF
GO


-- NS 2/16/2007


CREATE FUNCTION [dbo].[OUTLOOK_fn_Get_Facstaff_Addresses_Country](@FSID INT, @ACode INT)
	RETURNS VARCHAR(100)
	AS
BEGIN

DECLARE @NATION_NAME VARCHAR(100) 
		
SET @NATION_NAME = ''   

SELECT DISTINCT @NATION_NAME = PETNCH.NATION_NAME
FROM  dbo.Facstaff_Addresses FSA  
	LEFT OUTER JOIN DECISION_SUPPORT.dbo.PUBLIC_EDW_T_NATION_CD_HIST PETNCH 
		ON FSA.Country = PETNCH.NATION_CD 			
WHERE   FSA.Facstaff_ID = @FSID AND 
	FSA.Address_Type_Code = @ACode  AND
	FSA.Active_Indicator = 1


IF  @NATION_NAME IS NULL
	SET  @NATION_NAME = ''
ELSE IF  @NATION_NAME = 'United States Of America'
	SET @NATION_NAME = 'USA'

	
RETURN(@NATION_NAME)
END



GO
