SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
/****** Script for SelectTopNRows command from SSMS  ******/

-- NS 4/20/2017
CREATE PROC [dbo].[Adhoc_sp_Get_Duplicates_UPLOAD_EDW_Current_Employees]
AS
SELECT TOP 1000 [EDW_PERS_ID]
      ,[UIN]
      ,[EDW_Database]
      ,[PERS_PREFERRED_FNAME]
      ,[PERS_FNAME]
      ,[PERS_MNAME]
      ,[PERS_LNAME]
      ,[BIRTH_DT]
      ,[SEX_CD]
      ,[RACE_ETH_CD]
      ,[RACE_ETH_DESC]
      ,[PERS_CITZN_TYPE_DESC]
      ,[EMPEE_CAMPUS_CD]
      ,[EMPEE_CAMPUS_NAME]
      ,[EMPEE_COLL_CD]
      ,[EMPEE_COLL_NAME]
      ,[EMPEE_DEPT_CD]
      ,[EMPEE_DEPT_NAME]
      ,[JOB_DETL_TITLE]
      ,[JOB_DETL_FTE]
      ,[JOB_CNTRCT_TYPE_DESC]
      ,[JOB_DETL_COLL_CD]
      ,[JOB_DETL_COLL_NAME]
      ,[JOB_DETL_DEPT_CD]
      ,[JOB_DETL_DEPT_NAME]
      ,[COA_CD]
      ,[ORG_CD]
      ,[EMPEE_ORG_TITLE]
      ,[EMPEE_CLS_CD]
      ,[EMPEE_CLS_LONG_DESC]
      ,[EMPEE_GROUP_CD]
      ,[EMPEE_GROUP_DESC]
      ,[EMPEE_RET_IND]
      ,[EMPEE_LEAVE_CATGRY_CD]
      ,[EMPEE_LEAVE_CATGRY_DESC]
      ,[BNFT_CATGRY_CD]
      ,[BNFT_CATGRY_DESC]
      ,[HR_CAMPUS_CD]
      ,[HR_CAMPUS_NAME]
      ,[EMPEE_STATUS_CD]
      ,[EMPEE_STATUS_DESC]
      ,[CAMPUS_JOB_DETL_FTE]
      ,[COLLEGE_JOB_DETL_FTE]
      ,[Univ_Sum_FTE]
      ,[Sum_FTE]
      ,[FAC_RANK_CD]
      ,[FAC_RANK_DESC]
      ,[FAC_RANK_ACT_DT]
      ,[FAC_RANK_DECN_DT]
      ,[FAC_RANK_ACAD_TITLE]
      ,[FAC_RANK_EMRTS_STATUS_IND]
      ,[FIRST_HIRE_DT]
      ,[CUR_HIRE_DT]
      ,[FIRST_WORK_DT]
      ,[LAST_WORK_DT]
      ,[EMPEE_TERMN_DT]
      ,[JOB_SUFFIX]
      ,[POSN_NBR]
      ,[JOB_DETL_EEO_SKILL_CD]
      ,[JOB_DETL_EEO_SKILL_DESC]
      ,[JOB_DETL_EFF_DT]
      ,[POSN_EMPEE_CLS_CD]
      ,[POSN_EMPEE_CLS_LONG_DESC]
      ,[EMPEE_SUB_DEPT_LEVEL_6_CD]
      ,[EMPEE_SUB_DEPT_LEVEL_6_NAME]
      ,[EMPEE_SUB_DEPT_LEVEL_7_CD]
      ,[EMPEE_SUB_DEPT_LEVEL_7_NAME]
      ,[NATION_CD]
      ,[Network_ID]
      ,[Update_Employee_Indicator]
      ,[New_Download_Indicator]
      ,[DM_Upload_Done_Indicator]
      ,[Create_Datetime]
  FROM [DM_Shadow_Staging].[dbo].[_UPLOAD_EDW_Current_Employees]
  where New_Download_Indicator=1
	AND [Update_Employee_Indicator] is not null
	AND EMPEE_CLS_CD NOT IN ('GA','SA', 'HG')
	AND  [EDW_PERS_ID] IN 
	  (SELECT [EDW_PERS_ID]
	  FROM [DM_Shadow_Staging].[dbo].[_UPLOAD_EDW_Current_Employees]
	  WHERE New_Download_Indicator=1
			AND [Update_Employee_Indicator] is not null
			AND EMPEE_CLS_CD NOT IN ('GA','SA', 'HG')
	  GROUP BY [EDW_PERS_ID]
	  HAVING COUNT(*) > 1 )
  ORDER BY [EDW_PERS_ID]
GO
