SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
-- STC 2/4/26 - Just a temporary test SP for Git testing

CREATE PROCEDURE [dbo].[_STC_Git_Test] 
AS
BEGIN
	SELECT *
	FROM INFORMATION_SCHEMA.TABLES
END
GO
