SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- NS 6/15/2016

CREATE PROCEDURE [dbo].[FSDB_STAGING1_SP_LOG_POST]
	@WHAT_LOADED VARCHAR(50),
	@LOAD_STATUS VARCHAR(50),
	@LOAD_DESC VARCHAR(200)
AS
	BEGIN

		-- EXEC dbo.[FSDB_STAGING1_SP_LOG_POST] 'USERS', 'OK', 'Everything is OK, test'
		INSERT INTO dbo.webservices_logs
		(
			POST_OR_GET,
			WHAT_LOADED,
			LOAD_STATUS_CD,
			LOAD_STATUS_DESC,
			POST_DATE
		)
		VALUES 
		(
			'POST',
			@WHAT_LOADED, 
			@LOAD_STATUS, 
			@LOAD_DESC,
			GETDATE()	
		)

	END

GO
