SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO


-- NS 8/22/2017: Revisited
-- NS 4/7/2017: Revisited
-- NS 11/16/2016: have not started coding yet, this is a copy from dbo.produce_XML_new_banner
CREATE PROC [dbo].[produce_XML_BANNER] ( @submit BIT=0 )
AS


--IF EXISTS (
--	SELECT 1
--	FROM dbo.webservices_requests
--	WHERE url LIKE '%/User/%'
--	HAVING -- last shadowed < last refreshed
--	MAX(CASE WHEN method='GET' AND processed IS NOT NULL THEN initiated ELSE NULL END) < MAX(CASE WHEN method<>'GET' THEN created ELSE NULL END)
--) RAISERROR('This data has not been shadowed since the last refresh.',18,1);
--ELSE 

BEGIN

	/*
	Test the results
	 EXEC dbo.[produce_XML_BANNER] @submit = 0

	 Manual run to upload USERS FROM FSDB
	 EXEC dbo.[produce_XML_BANNER] @submit = 1
	 EXEC dbo.webservices_run_DTSX
	*/

	 EXEC dbo.[produce_XML_BANNER_current] @submit = 1
	 EXEC dbo.[produce_XML_BANNER_new] @submit = 1
	 EXEC dbo.webservices_run_DTSX

/*
<Data>
<Record username="aa311096">

<BANNER>
<FACSTAFFID>101605</FACSTAFFID>
<EDWPERSID>2224543</EDWPERSID><UIN>667782578</UIN>
<PERS_PREFERRED_FNAME>&#x20;</PERS_PREFERRED_FNAME>
<PERS_FNAME>Mary Frances</PERS_FNAME>
<PERS_MNAME>&#x20;</PERS_MNAME>
<PERS_LNAME>Fagan</PERS_LNAME>
<BIRTH_DT>1954-10-09T00:00:00</BIRTH_DT>
<SEX_CD>Female</SEX_CD>
<RACE_ETH_DESC>White, Non-Hispanic</RACE_ETH_DESC>
<PERS_CITZN_TYPE_DESC>Citizen</PERS_CITZN_TYPE_DESC>

<EMPEE_CAMPUS_CD>1</EMPEE_CAMPUS_CD>
<EMPEE_CAMPUS_NAME>Urbana-Champaign Campus</EMPEE_CAMPUS_NAME>
<EMPEE_COLL_CD>KM</EMPEE_COLL_CD>
<EMPEE_COLL_NAME>Gies College of Business</EMPEE_COLL_NAME>
<EMPEE_DEPT_CD>747</EMPEE_DEPT_CD>
<EMPEE_DEPT_NAME>Gies Mktg &amp; Communications</EMPEE_DEPT_NAME>

<JOB_DETL_TITLE>ACADEMIC HRLY ADMIN</JOB_DETL_TITLE>
<JOB_DETL_FTE>0.000</JOB_DETL_FTE>
<JOB_CNTRCT_TYPE_DESC>Primary</JOB_CNTRCT_TYPE_DESC>
<JOB_DETL_COLL_CD>KM</JOB_DETL_COLL_CD>
<JOB_DETL_COLL_NAME>Gies College of Business</JOB_DETL_COLL_NAME>
<JOB_DETL_DEPT_CD>747</JOB_DETL_DEPT_CD>
<JOB_DETL_DEPT_NAME>Gies Mktg &amp; Communications</JOB_DETL_DEPT_NAME>

<COA_CD>1</COA_CD>
<ORG_CD>747000</ORG_CD>
<EMPEE_ORG_TITLE>Gies Mktg &amp; Communications</EMPEE_ORG_TITLE>
<EMPEE_CLS_CD>HA</EMPEE_CLS_CD>
<EMPEE_CLS_LONG_DESC>Hrly Faculty/Clinical/Research</EMPEE_CLS_LONG_DESC>
<EMPEE_GROUP_CD>H</EMPEE_GROUP_CD>
<EMPEE_GROUP_DESC>Academic Hourly &amp; Grad Hourly</EMPEE_GROUP_DESC>
<EMPEE_RET_IND>No</EMPEE_RET_IND>
<EMPEE_LEAVE_CATGRY_CD>IN</EMPEE_LEAVE_CATGRY_CD>
<EMPEE_LEAVE_CATGRY_DESC>Ineligible</EMPEE_LEAVE_CATGRY_DESC>
<BNFT_CATGRY_CD>B4</BNFT_CATGRY_CD>
<BNFT_CATGRY_DESC>Bi-Weekly Statutory Only</BNFT_CATGRY_DESC>
<HR_CAMPUS_CD>U</HR_CAMPUS_CD>
<HR_CAMPUS_NAME>UIUC Urbana / Champaign</HR_CAMPUS_NAME>
<EMPEE_STATUS_CD>A</EMPEE_STATUS_CD>
<EMPEE_STATUS_DESC>Active</EMPEE_STATUS_DESC>

<CAMPUS_JOB_DETL_FTE>0.000</CAMPUS_JOB_DETL_FTE>
<COLLEGE_JOB_DETL_FTE>0.000</COLLEGE_JOB_DETL_FTE>
<FAC_RANK_EMRTS_STATUS_IND>No</FAC_RANK_EMRTS_STATUS_IND>
<FIRST_HIRE_DT>2016-12-05T00:00:00</FIRST_HIRE_DT>
<CUR_HIRE_DT>2016-12-05T00:00:00</CUR_HIRE_DT>
<FIRST_WORK_DT>2016-12-05T00:00:00</FIRST_WORK_DT>

<Network_ID>aa311096</Network_ID>

</BANNER>

</Record>
</Data>

*/

	END

GO
