CREATE TABLE [dbo].[AACSB_2_1_Pubs]
(
[Log_ID] [int] NOT NULL,
[Facstaff_ID] [int] NOT NULL,
[AACSB_Department] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Author_Share] [float] NULL,
[Author_Name] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Authors] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IC_Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Gies_IC_Type] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Refereed] [bit] NULL,
[AJ Confirmed] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Classified] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AACSB_Class] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Journal_Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pub_Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Range_Boundary] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[RP_Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Name] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Research_Publication_ID] [int] NOT NULL,
[Research_Publication_Type] [int] NOT NULL,
[Research_Publication_Title] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sub_Title] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Research_Publication_Contribution_Type] [int] NULL,
[Research_Publication_Sub_Type] [int] NULL,
[Book_Role_ID] [int] NULL,
[Scope_ID] [int] NULL,
[Research_Publication_Refereed_Indicator] [bit] NULL,
[Editorial_Indicator] [bit] NULL,
[Journal_ID] [int] NULL,
[Conference_ID] [int] NULL,
[Research_Publication_Pages] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Publication_Issue_ID] [int] NULL,
[Publisher_ID] [int] NULL,
[Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Accepted_Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Published_Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Volume] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Research_Publication_Description] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Research_Publication_Status_Indicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Invited_Indicator] [bit] NULL,
[Conference_Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_Country] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_Month] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Full_Paper_Indicator] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Editor] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revision_Indicator] [bit] NULL,
[Under_Review_Indicator] [bit] NULL,
[SSRN_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOI] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Perennial_Display_Indicator] [bit] NULL,
[Active_Indicator] [bit] NULL,
[Create_Datetime] [datetime] NULL,
[Last_Update_Datetime] [datetime] NULL,
[Last_Update_Network_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pub_Status] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Pub_Title] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Book_Title] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Num] [int] NOT NULL
) ON [PRIMARY]
GO
