CREATE TABLE [dbo].[AACSB_Positions_Report]
(
[facstaff_ID] [int] NOT NULL,
[AACSB_Type] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AACSB_Department] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Full_Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AACSB_Date] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AACSB_Ac_Years] [int] NULL,
[AACSB_Cal_Years] [int] NULL,
[All] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2013] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2014] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2015] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2016] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2017] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[2018] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Ac Pos] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AP 13] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AP 14] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AP 15] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AP 16] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AP 17] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AP 18] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Ac Org] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AO 13] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AO 14] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AO 15] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AO 16] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AO 17] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[AO 18] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Prof] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[P 13] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[P 14] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[P 15] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[P 16] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[P 17] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[P 18] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Cons] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C 13] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C 14] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C 15] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C 16] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C 17] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[C 18] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
