CREATE TABLE [dbo].[Courses_BUS_AACSB]
(
[Courses_BUS_ID] [int] NOT NULL,
[Facstaff_ID] [int] NULL,
[AACSB_Instructor] [bit] NULL,
[AACSB_Section] [bit] NULL,
[EDW_PERS_ID] [decimal] (9, 0) NOT NULL,
[TERM_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[TERM_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRS_ID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRS_TITLE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRS_SUBJ_CD] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRS_NBR] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[CRS_DESC_TXT] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRN] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SECT_NBR] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SECT_LINK_ID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LINKED_SECT_ID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCHED_TYPE_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[SCHED_TYPE_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_FNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_MNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_LNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_NAME_SUFFIX] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_PREFERRED_FNAME] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_LEVEL] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_REPEAT_STATUS_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CENSUS_ENROLL] [int] NULL,
[ENROLL] [decimal] (8, 2) NULL,
[CHOURS] [decimal] (4, 2) NULL,
[DMI_HOURS] [decimal] (6, 2) NULL,
[FAC_ASSIGN_RESP_PCT] [int] NULL,
[CHOURS_TXT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DMI_HOURS_TXT] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CENSUS_TWO_ENRL] [int] NULL,
[SECT_CENSUS_ENRL_NBR] [int] NULL,
[CRS_CONTACT_HOUR_IND] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_MIN_CONTACT_HOUR] [decimal] (6, 2) NULL,
[CRS_MAX_CONTACT_HOUR] [decimal] (6, 2) NULL,
[CREDIT_HOUR] [decimal] (7, 3) NULL,
[CRS_VAR_CREDIT_HOUR_IND] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CRS_MIN_CREDIT_HOUR_NBR] [decimal] (4, 2) NULL,
[CRS_MAX_CREDIT_HOUR_NBR] [decimal] (4, 2) NULL,
[PART_OF_TERM_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Num_Instructors] [int] NULL,
[Num_AACSB_Instructors] [int] NULL,
[Num_Course_Instructors] [int] NULL,
[Num_Course_AACSB_Instructors] [int] NULL,
[Course_Load_Weight] [float] NULL,
[CRN_Enroll] [int] NULL,
[CRS_Enroll] [int] NULL,
[CRN_SCH] [int] NULL,
[CRS_SCH] [int] NULL,
[Num_Resp_Instructors] [int] NULL,
[AACSB_Resp_Instructors] [int] NULL,
[CRN_Resp_Total] [int] NULL,
[AACSB_Resp_Total] [int] NULL,
[Resp_Share] [float] NULL,
[AACSB_Resp_Share] [float] NULL,
[Qualification] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCH_Share] [float] NULL,
[Ignore_Flag] [bit] NULL,
[T15_1_Course] [bit] NULL,
[Num_Course_Load_Instructors] [int] NULL,
[iDegree_Course] [bit] NULL,
[T15_1_Course_Weight] [float] NULL,
[T15_1_Instr_Course_Load] [float] NULL
) ON [PRIMARY]
GO
