CREATE TABLE [dbo].[_DM_INTELLCONT]
(
[id] [bigint] NOT NULL,
[Research_Publication_ID] [int] NULL,
[CLASSIFICATION] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTYPE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONTYPEOTHER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TITLE] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STATUS] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOURNAL_REF] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOURNAL_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOURNAL_NAME] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOURNAL_REFEREED] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CONFERENCE] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PUBLISHER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PUBCTYST] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[VOLUME] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISSUE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PAGENUM] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[REVISED] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INVITED] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UNDER_REVIEW] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EDITORS] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_EXPSUB] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_EXPSUB] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_SUB] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_SUB] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_ACC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_ACC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_PUB] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_PUB] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESC] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SCOPE_LOCALE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PUBLICAVAIL] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ABSTRACT] [varchar] (5000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEB_ADDRESS] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSRN] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[DOI] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ISBNISSN] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Research_Publication_Type_Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Missing_Google_ID] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Missing_Book_Role] [nchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Missing_PERENNIAL] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastModified] [datetime] NULL,
[Create_Datetime] [datetime] NULL,
[Download_Datetime] [datetime] NULL
) ON [PRIMARY]
GO
