CREATE TABLE [dbo].[AACSB_2_1_ICs]
(
[Log_ID] [int] NOT NULL,
[Facstaff_ID] [int] NOT NULL,
[AACSB_Department] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Author_Share] [float] NULL,
[Author_Name] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IC_Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Gies_IC_Type] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Classified] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Classification] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Authors] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IC ID] [int] NOT NULL,
[Title] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Journal or Agency] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Book Title] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Date Boundary] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Start Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[End Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Amount] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Description] [varchar] (400) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Volume] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Number] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pages] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pub Type] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Refereed] [bit] NULL,
[Editorial] [bit] NULL,
[AJ Confirmed] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Editor] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Research_Publication_Contribution_Type] [int] NULL,
[Research_Publication_Type] [int] NULL,
[Research_Publication_Sub_Type] [int] NULL,
[Journal_ID] [int] NULL,
[Conference_ID] [int] NULL,
[Publication_Issue_ID] [int] NULL,
[Publisher_ID] [int] NULL,
[Invited_Indicator] [bit] NULL,
[Conference_Name] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_City] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_State] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_Country] [varchar] (5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Conference_Month] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Pub_Status] [varchar] (14) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Month_Num] [int] NULL,
[Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Accepted_Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Published_Year] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Revision_Indicator] [bit] NULL,
[SSRN_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOI] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Create_Datetime] [datetime] NULL,
[Last_Update_Datetime] [datetime] NULL,
[Last_Update_Network_ID] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
