CREATE TABLE [dbo].[_Archive_FSDB_EDW_Current_Employees]
(
[EDW_PERS_ID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UIN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Network_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EDW_Database] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_PREFERRED_FNAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_FNAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_MNAME] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_LNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTH_DT] [datetime] NULL,
[SEX_CD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RACE_ETH_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RACE_ETH_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_CITZN_TYPE_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CAMPUS_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CAMPUS_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_COLL_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_COLL_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_DEPT_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_DEPT_NAME] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_TITLE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_FTE] [decimal] (9, 3) NULL,
[JOB_CNTRCT_TYPE_DESC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_DATA_STATUS_DESC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_COLL_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_COLL_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_DEPT_CD] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_DEPT_NAME] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COA_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_ORG_TITLE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CLS_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CLS_LONG_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_GROUP_CD] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_GROUP_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_RET_IND] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_LEAVE_CATGRY_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_LEAVE_CATGRY_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNFT_CATGRY_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNFT_CATGRY_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HR_CAMPUS_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HR_CAMPUS_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_STATUS_CD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_STATUS_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPUS_JOB_DETL_FTE] [decimal] (9, 3) NULL,
[COLLEGE_JOB_DETL_FTE] [decimal] (9, 3) NULL,
[Univ_Sum_FTE] [decimal] (9, 3) NULL,
[Sum_FTE] [decimal] (9, 3) NULL,
[FAC_RANK_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_DESC] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_ACT_DT] [datetime] NULL,
[FAC_RANK_DECN_DT] [datetime] NULL,
[FAC_RANK_ACAD_TITLE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_EMRTS_STATUS_IND] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TENURE_INDICATOR] [bit] NULL CONSTRAINT [DF_FSDB_EDW_Current_Employees_TENURE_INDICATOR] DEFAULT ((0)),
[FIRST_HIRE_DT] [datetime] NULL,
[CUR_HIRE_DT] [datetime] NULL,
[FIRST_WORK_DT] [datetime] NULL,
[LAST_WORK_DT] [datetime] NULL,
[EMPEE_TERMN_DT] [datetime] NULL,
[JOB_SUFFIX] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSN_NBR] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_EEO_SKILL_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_EEO_SKILL_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_EFF_DT] [datetime] NULL,
[POSN_EMPEE_CLS_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSN_EMPEE_CLS_LONG_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_SUB_DEPT_LEVEL_6_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_SUB_DEPT_LEVEL_6_NAME] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_SUB_DEPT_LEVEL_7_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_SUB_DEPT_LEVEL_7_NAME] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NATION_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Update_Employee_Indicator] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_Download_Indicator] [bit] NULL,
[DM_Upload_Done_Indicator] [bit] NULL CONSTRAINT [DF_EDW_Current_Employees_DM_Download_Indicator] DEFAULT ((1)),
[Create_Datetime] [datetime] NULL
) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FSDB_EDW_Current_Employees_Create_Datetime] ON [dbo].[_Archive_FSDB_EDW_Current_Employees] ([Create_Datetime]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FSDB_EDW_Current_Employees_EDW_PERS_ID] ON [dbo].[_Archive_FSDB_EDW_Current_Employees] ([EDW_PERS_ID]) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_FSDB_EDW_Current_Employees_JOB_CONTRCT_TYPE_DESC] ON [dbo].[_Archive_FSDB_EDW_Current_Employees] ([JOB_CNTRCT_TYPE_DESC]) ON [PRIMARY]
GO
