CREATE TABLE [dbo].[_UPLOADED_DM_PCI]
(
[userid] [bigint] NULL,
[ID] [bigint] NULL,
[surveyID] [bigint] NULL,
[termID] [bigint] NULL,
[FACSTAFFID] [int] NULL,
[EDWPERSID] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[USERNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[MNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PFNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PMNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMAIL] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_DOB] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTD_DOB] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_DOB] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB_START] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOB_END] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GENDER] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ETHNICITY] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CITIZEN] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SSRN_ID] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[GOOGLE_SCHOLAR_ID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORCID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIO_SKETCH] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROF_INTERESTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TEACHING_INTERESTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RESEARCH_INTERESTS] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPLOAD_CV] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHOW_CV] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UPLOAD_PHOTO] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHOW_PHOTO] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHOW_COLLEGE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHOW_DEPT] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SHOW_PROFILE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PROFILE_ID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[STAFF_CLASS] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RANK] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOC_STATUS] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOC_DEPT] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DOC_TERM] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUS_PERSON] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUS_FACULTY] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ACTIVE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Create_datetime] [datetime] NULL,
[lastModified] [datetime] NULL
) ON [PRIMARY]
GO
