CREATE TABLE [dbo].[_DM_DEG_COMMITTEE]
(
[userid] [bigint] NULL,
[id] [bigint] NOT NULL,
[USERNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FACSTAFFID] [int] NULL,
[EDWPERSID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UIN] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INSTITUTION] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[INSTITUTION_OTHER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DEP_OTHER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TYPE_OTHER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ROLE_OTHER] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_START] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[START_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[START_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_END] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[END_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[END_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_PRELIM_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_PRELIM_START] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRELIM_START_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRELIM_START_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_PRELIM_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_PRELIM_END] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRELIM_END_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PRELIM_END_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_FINAL_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_FINAL_START] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FINAL_START_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FINAL_START_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTM_FINAL_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DTY_FINAL_END] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FINAL_END_START] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FINAL_END_END] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DESC] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TITLE] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PLACEMENT] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[WEB_PROFILE] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lastModified] [datetime] NULL,
[Create_Datetime] [datetime] NULL,
[Download_Datetime] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[_DM_DEG_COMMITTEE] ADD CONSTRAINT [PK__DM_DEG_COMMITTEE] PRIMARY KEY CLUSTERED ([id]) ON [PRIMARY]
GO
