CREATE TABLE [dbo].[AACSB_2_1_Table]
(
[Log_ID] [int] NOT NULL,
[Type] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Facstaff ID] [int] NOT NULL,
[Department] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Name] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Basic] [float] NULL,
[Applied] [float] NULL,
[Teaching] [float] NULL,
[Unclassified] [float] NULL,
[Classified Total] [float] NULL,
[PRJ Articles] [float] NULL,
[ERJ Articles] [float] NULL,
[Proceedings] [float] NULL,
[Presentations] [float] NULL,
[Textbooks] [float] NULL,
[Research Awards] [float] NULL,
[Case Studies] [float] NULL,
[Policy & Standards] [float] NULL,
[Books] [float] NULL,
[Chapters] [float] NULL,
[Online Courses] [float] NULL,
[CPE] [float] NULL,
[Non-Review] [float] NULL,
[Non-Academic] [float] NULL,
[Others] [float] NULL,
[Total Others] [float] NULL,
[IC Total] [float] NULL,
[Participating IC %] [float] NULL,
[Full Time IC %] [float] NULL,
[Num Participating] [float] NULL,
[Num Participating ICs] [float] NULL,
[Num Full Time] [float] NULL,
[Num Full Time ICs] [float] NULL
) ON [PRIMARY]
GO
