CREATE TABLE [dbo].[_UPLOADED_DM_BANNER]
(
[USERNAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ID] [int] NULL,
[FACSTAFFID] [int] NULL,
[EDWPERSID] [varchar] (12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UIN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EDW_Database] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_PREFERRED_FNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_FNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_MNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_LNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BIRTH_DT] [datetime] NULL,
[SEX_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[RACE_ETH_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_CITZN_TYPE_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CAMPUS_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CAMPUS_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_COLL_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_COLL_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_DEPT_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_DEPT_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_TITLE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_FTE] [decimal] (9, 3) NULL,
[JOB_CNTRCT_TYPE_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_COLL_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_COLL_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_DEPT_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_DEPT_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[COA_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORG_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_ORG_TITLE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CLS_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CLS_LONG_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_GROUP_CD] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_GROUP_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_RET_IND] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_LEAVE_CATGRY_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_LEAVE_CATGRY_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNFT_CATGRY_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BNFT_CATGRY_DESC] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HR_CAMPUS_CD] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[HR_CAMPUS_NAME] [varchar] (60) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_STATUS_CD] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_STATUS_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CAMPUS_JOB_DETL_FTE] [decimal] (9, 3) NULL,
[COLLEGE_JOB_DETL_FTE] [decimal] (9, 3) NULL,
[FAC_RANK_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_DESC] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_ACT_DT] [datetime] NULL,
[FAC_RANK_DECN_DT] [datetime] NULL,
[FAC_RANK_ACAD_TITLE] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_EMRTS_STATUS_IND] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FIRST_HIRE_DT] [datetime] NULL,
[CUR_HIRE_DT] [datetime] NULL,
[FIRST_WORK_DT] [datetime] NULL,
[LAST_WORK_DT] [datetime] NULL,
[EMPEE_TERMN_DT] [datetime] NULL,
[Network_ID] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Record_Status] [varchar] (3) COLLATE SQL_Latin1_General_CP1_CI_AS NULL CONSTRAINT [DF__UPLOADED_DM_BANNER_New_Record_Indicator] DEFAULT ('CUR'),
[Update_Status] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Create_Datetime] [datetime] NULL,
[Last_Update_Datetime] [datetime] NULL
) ON [PRIMARY]
GO
EXEC sp_addextendedproperty N'MS_Description', N'CUR (still working today emps), NEW (new emps), or END (terminated emps)', 'SCHEMA', N'dbo', 'TABLE', N'_UPLOADED_DM_BANNER', 'COLUMN', N'Record_Status'
GO
EXEC sp_addextendedproperty N'MS_Description', N'update to P=PCI, U=USERS, B=BANNER screens, N=username changed', 'SCHEMA', N'dbo', 'TABLE', N'_UPLOADED_DM_BANNER', 'COLUMN', N'Update_Status'
GO
