CREATE TABLE [dbo].[Facstaff_AACSB]
(
[Facstaff_ID] [int] NOT NULL,
[Full_Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AACSB_Department] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Discipline1] [int] NULL,
[Discipline2] [int] NULL,
[Specialty] [int] NULL,
[NPR_Administration] [bit] NULL,
[NPR_Doctoral] [bit] NULL,
[NPR_Executive] [bit] NULL,
[NPR_Masters] [bit] NULL,
[NPR_Research] [bit] NULL,
[NPR_Undergrad] [bit] NULL,
[NPR_Other] [bit] NULL,
[Percent_Time] [decimal] (5, 3) NULL,
[Qualification] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qualification_Description] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sufficiency] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Joint_Appointment] [bit] NULL,
[Highest_Degree] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Degree_Year] [int] NULL,
[First_Appointment_Date] [datetime] NULL,
[Exclude_Flag] [bit] NULL,
[Exclude_T31_Flag] [bit] NULL,
[Exclude_T32_Flag] [bit] NULL,
[FTE] [decimal] (5, 3) NULL,
[First_Appt_Date_Orig] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Research_PhD_Flag] [bit] NULL,
[Professional_Experience_Flag] [bit] NULL,
[Professional_Certification_Flag] [bit] NULL,
[Dept_Rank] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Qualification_Justification] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes1] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Notes2] [varchar] (1000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_Update_Datetime] [datetime] NULL,
[CUR_HIRE_DT] [datetime] NULL,
[EDW_PERS_ID] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Network_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UIN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FSDB_Facstaff_ID] [int] NULL,
[Academic_Year] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Facstaff_AACSB] ADD CONSTRAINT [PK_Facstaff_AACSB] PRIMARY KEY CLUSTERED ([Facstaff_ID], [Academic_Year]) ON [PRIMARY]
GO
