CREATE TABLE [dbo].[FSDB_Facstaff_Basic]
(
[Facstaff_ID] [int] NOT NULL IDENTITY(1, 1),
[UIN] [varchar] (9) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EDW_PERS_ID] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_DEPT_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_DEPT_NAME] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CLS_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_CLS_LONG_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSN_EMPEE_CLS_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSN_EMPEE_CLS_LONG_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_GROUP_CD] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EMPEE_GROUP_DESC] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[POSN_NBR] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_DEPT_CD] [varchar] (4) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_DEPT_NAME] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_TITLE] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_DETL_FTE] [decimal] (9, 0) NULL,
[JOB_CNTRCT_TYPE_DESC] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[JOB_SUFFIX] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_CD] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_DESC] [varchar] (35) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_ACT_DT] [datetime] NULL,
[FAC_RANK_DECN_DT] [datetime] NULL,
[FAC_RANK_ACAD_TITLE] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FAC_RANK_EMRTS_STATUS_IND] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_CITZN_TYPE_DESC] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Network_ID] [varchar] (8) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[College_Sum_FTE] [int] NULL,
[Univ_Sum_FTE] [int] NULL,
[Non_BUS_Person_Institution] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BUS_Person_Indicator] [bit] NOT NULL,
[SSRN_ID] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ORCID] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Google_Scholar_ID] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department_ID] [int] NULL,
[DM_Department_Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Department_Subgroup_ID] [int] NULL,
[Last_Name] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[PERS_MNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Middle_Name] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[First_Name] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[PERS_PREFERRED_FNAME] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Professional_Last_Name] [varchar] (120) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Faculty_Staff_Indicator] [bit] NULL,
[Graduate_Assistant_Indicator] [bit] NULL,
[Staff_Classification_ID] [int] NULL,
[Campus_Wide_Appointment_Percent] [int] NULL,
[Appointment_Percent] [int] NULL,
[Appointment_Type_Indicator] [bit] NULL,
[Current_Status_Indicator] [bit] NULL,
[Tenure_Status_Indicator] [bit] NULL,
[Tenure_Track_Status_Indicator] [bit] NULL,
[Third_Year_Review_Status] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Rank_ID] [int] NULL,
[Title_ID] [int] NULL,
[Email_Address] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Home_Page] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Teaching_Interests] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Research_Interests] [varchar] (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Ethnicity_ID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Citizenship_ID] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Gender] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Birth_Date] [datetime] NULL,
[Hired_Date] [datetime] NULL,
[Leaving_Date] [datetime] NULL,
[Teaching_MBA_Indicator] [bit] NULL,
[Emergency_Contact_Name] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Emergency_Contact_Type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Emergency_Contact_Phone_International_Access] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Emergency_Contact_Phone_Area_Code] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Emergency_Contact_Phone_Number] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Emergency_Contact_Phone_Extension] [varchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[College_List_Indicator] [bit] NULL,
[Department_List_Indicator] [bit] NULL,
[Biographical_Sketch] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Create_Datetime] [datetime] NULL,
[Last_Update_Datetime] [datetime] NULL,
[Active_Indicator] [bit] NULL,
[Bus_Person_Manual_Entry_Indicator] [bit] NULL,
[College_Directory_Indicator] [bit] NULL,
[Doctoral_Flag] [smallint] NULL,
[Doctoral_Department_ID] [smallint] NULL,
[Doctoral_Award_Term_CD] [varchar] (6) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Last_EDW_Update_Datetime] [datetime] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FSDB_Facstaff_Basic] ADD CONSTRAINT [PK_Facstaff_Basic] PRIMARY KEY CLUSTERED ([Facstaff_ID]) ON [PRIMARY]
GO
